name: femvitalis
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2 # Optional for typing effect
  intl: ^0.18.0
  table_calendar: ^3.0.8
  flutter_local_notifications: ^12.0.0
  firebase_core: ^3.13.0
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.3.0
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/images/img6.png
    - assets/images/img7.png
    - assets/images/Poppy_seed.jpg
    - assets/images/Chia_seed.jpg
    - assets/images/apple_seed.jpg
    - assets/images/watermelon_seed.jpg
    - assets/images/nutrition1.jpeg
    - assets/images/nutrition2.jpg
    - assets/images/nutrition3.jpeg
    - assets/images/nutrition4.png
    - assets/images/nutrition5.png
    - assets/images/nutrition6.png
    - assets/images/nutrition7.png
    - assets/images/nutrition8.png
    - assets/images/nutrition9.png
    - assets/images/nutrition10.png
    - assets/images/body1.jpeg
    - assets/images/body2.jpeg
    - assets/images/body3.jpeg
    - assets/images/body4.jpeg
    - assets/images/body5.jpeg
    - assets/images/body6.jpeg
    - assets/images/body7.jpeg
    - assets/images/body8.jpeg
    - assets/images/body9.jpeg
    - assets/images/body10.jpeg
    - assets/images/baby1.jpeg
    - assets/images/baby2.jpeg
    - assets/images/baby3.jpeg
    - assets/images/baby4.jpeg
    - assets/images/baby5.jpeg
    - assets/images/baby6.jpeg
    - assets/images/baby7.jpeg
    - assets/images/baby8.jpeg
    - assets/images/baby9.jpeg
    - assets/images/baby10.jpeg
    - assets/images/myth1.jpeg
    - assets/images/myth2.jpeg
    - assets/images/myth3.jpeg
    - assets/images/myth4.jpeg
    - assets/images/myth5.jpeg
    - assets/images/myth6.jpeg
    - assets/images/myth7.jpeg
    - assets/images/myth8.jpeg
    - assets/images/myth9.jpeg
    - assets/images/myth10.jpeg


    - assets/images/week1.jpg
    - assets/images/week2.jpg
    - assets/images/week3.jpg
    - assets/images/week4.jpeg
    - assets/images/week5.jpg
    - assets/images/week6.jpeg
    - assets/images/week7.png
    - assets/images/week8.png
    - assets/images/week9.png
    - assets/images/week10.png
    - assets/images/pcos1.jpg

    # Add more images if needed later
    # - assets/images/hands.png
